<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Purchase History - {{ $vendor->firm_name }}</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #0d9488; padding-bottom: 15px; }
        .header h1 { margin: 0; color: #0d9488; font-size: 24px; }
        .header p { margin: 5px 0 0; color: #666; font-size: 14px; }
        .details { margin-bottom: 30px; width: 100%; border-collapse: collapse; }
        .details td { padding: 5px; vertical-align: top; }
        table.data-table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        table.data-table th, table.data-table td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        table.data-table th { background-color: #f8fafc; font-weight: bold; color: #0f172a; }
        table.data-table td.right { text-align: right; }
        table.data-table th.right { text-align: right; }
        .total-row { font-weight: bold; background-color: #f1f5f9; }
        .footer { margin-top: 40px; text-align: center; font-size: 10px; color: #94a3b8; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $vendor->firm_name }}</h1>
        <p>Purchase History Statement</p>
    </div>

    <table class="details">
        <tr>
            <td width="50%">
                <strong>Contact Person:</strong> {{ $vendor->contact_person ?: 'N/A' }}<br>
                <strong>Phone:</strong> {{ $vendor->phone }}<br>
                <strong>Location:</strong> {{ $vendor->location ?: 'N/A' }}
            </td>
            <td width="50%" style="text-align: right;">
                <strong>GSTIN:</strong> {{ $vendor->gst_number ?: 'UNREGISTERED' }}<br>
                <strong>Route:</strong> {{ $vendor->route ?: 'General' }}<br>
                <strong>Generated On:</strong> {{ now()->format('d M Y, h:i A') }}
            </td>
        </tr>
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Item Details</th>
                <th class="right">Quantity</th>
                <th class="right">Total Amount (Rs)</th>
            </tr>
        </thead>
        <tbody>
            @php $totalAmount = 0; @endphp
            @forelse($purchases as $purchase)
                @php $totalAmount += $purchase->total_amount; @endphp
                <tr>
                    <td>{{ $purchase->date->format('d M Y') }}</td>
                    <td>
                        @if($purchase->items->isNotEmpty())
                            {{ $purchase->items->pluck('item_name')->join(', ') }}
                        @else
                            {{ $purchase->item }}
                        @endif
                    </td>
                    <td class="right">
                        @if($purchase->items->isNotEmpty())
                            {{ number_format($purchase->items->sum('quantity'), 2) }} {{ $purchase->items->first()->unit }}
                        @else
                            {{ number_format($purchase->quantity, 2) }} {{ $purchase->unit }}
                        @endif
                    </td>
                    <td class="right">{{ number_format($purchase->total_amount, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" style="text-align: center; padding: 20px;">No purchases found.</td>
                </tr>
            @endforelse
            @if($purchases->count() > 0)
                <tr class="total-row">
                    <td colspan="3" class="right">Total Business Volume:</td>
                    <td class="right">Rs {{ number_format($totalAmount, 2) }}</td>
                </tr>
            @endif
        </tbody>
    </table>

    <div class="footer">
        Generated by Flockwise BizTrack &bull; Page 1 of 1
    </div>
</body>
</html>
